create database salesproject360 ;
use salesproject360;
show tables;
drop table sales360;
-- check the column--
describe sales360_order;
describe sales360customer;
describe sales360employee;
describe sales360payment;
describe sales360product;
describe sales360return;
-- check the data--
SELECT 
    *
FROM
    sales360_order
LIMIT 5;
SELECT 
    COUNT(*) AS order_count
FROM
    sales360_order;
SELECT 
    COUNT(*) AS customer_count
FROM
    sales360customer;
SELECT 
    COUNT(*) AS employee_count
FROM
    sales360customer;
SELECT 
    COUNT(*) AS payment_count
FROM
    sales360payment;
SELECT 
    COUNT(*) AS product_count
FROM
    sales360product;
SELECT 
    COUNT(*) AS return_count
FROM
    sales360return;
-- check for duplicates ID from table --
SELECT 
    *
FROM
    sales360_order;
SELECT 
    ORDERID, COUNT(*) AS count
FROM
    sales360_order
GROUP BY ORDERID
HAVING COUNT(*) > 1;
-- checking duplicates ID from customer table--
select * from sales360customer;
SELECT 
    CUSTOMERID, COUNT(*) AS COUNT
FROM
    sales360customer
GROUP BY CUSTOMERID
HAVING COUNT(*) > 1;
-- CHECKING DUPICATES FOR EMPLOYEE TABLE--
SELECT * FROM sales360employee;
SELECT 
    EMPID, COUNT(*) AS COUNT
FROM
    sales360employee
GROUP BY EMPID
HAVING COUNT(*) > 1;
-- CHECKING DUPLICATES FOR PAYMENT--
SELECT * FROM sales360payment;
SELECT 
    PAYMENTID, COUNT(*) AS COUNT
FROM
    sales360payment
GROUP BY PAYMENTID
HAVING COUNT(*) > 1;
-- CHECKING DUPICATES FOR PRODUCT TABLE--
SELECT * FROM sales360product ;
SELECT 
    PRODUCTID, COUNT(*) AS COUNT
FROM
    sales360product
GROUP BY PRODUCTID
HAVING COUNT(*) > 1;
-- CHECKING DUPLICATES FOR RETURN TABLE--
SELECT * FROM sales360return;
SELECT 
    RETURNID, COUNT(*) AS COUNT
FROM
    sales360return
GROUP BY RETURNID
HAVING COUNT(*) > 1;
-- CALCULATE TOTAL SALES--
SELECT SUM(O.QUANTITY * P.UNITPRICE)AS TOTAL_SALES FROM sales360_order O JOIN sales360product P ON 
O.PRODUCTID = P.PRODUCTID;
-- CALCULATE TOTAL SALES FOR INDIVIDUAL ORDERS --
SELECT 
    O.ORDERID,
    O.ORDERDATE,
    O.QUANTITY,
    P.UNITPRICE,
    (O.QUANTITY * P.UNITPRICE) AS SALES
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
LIMIT 10;
-- query for categorywise sales--
SELECT 
    P.CATEGORY, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
GROUP BY P.CATEGORY
ORDER BY TOTALSALES DESC;
-- WRITE A QUERY TO CATEGORY WISE ORDER AND QUANTITY--
SELECT 
    P.CATEGORY,
    COUNT(DISTINCT O.ORDERID) AS TOTALORDERS,
    SUM(O.QUANTITY) AS TOTAL_QUANTITY
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
GROUP BY P.CATEGORY
ORDER BY TOTALORDERS DESC;
-- WRITE A QUERY SUBCATEGORY WISE SALES--
SELECT 
    P.SUBCATEGORY, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product p ON O.PRODUCTID = P.PRODUCTID
GROUP BY P.SUBCATEGORY
ORDER BY TOTALSALES DESC;
-- QUERY FOR TOP 10 PRODUCT BY SALES--
SELECT 
    P.PRODUCTNAME, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
GROUP BY P.PRODUCTNAME
ORDER BY TOTALSALES DESC
LIMIT 10;
-- QUERY FOR TOP 10 CUSTOMER BY SALES--
SELECT 
    C.CUSTOMERID, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
        JOIN
    sales360customer C ON O.CUSTOMERID = C.CUSTOMERID
GROUP BY C.CUSTOMERID
ORDER BY TOTALSALES DESC
LIMIT 10;
-- QUERY EMPLOYEE WISE SALES--
describe sales360employee;
DESCRIBE sales360_order;
SELECT 
    E.EMPID,
    E.EMPNAME,
    SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
        JOIN
    sales360employee E ON O.EMPLOYEEID = E.EMPID
GROUP BY E.EMPID , EMPNAME
ORDER BY TOTALSALES DESC;
-- QUERY FOR PAYEMENT STATUS ANALYSIS--
-- QUERY TO COUNT PAYMENT STATUS --
SELECT 
    PAYMENTSTATUS, COUNT(PAYMENTID) AS PAYMENTCOUNT
FROM
    sales360payment
GROUP BY PAYMENTSTATUS
ORDER BY PAYMENTCOUNT DESC;
-- PAYMENT METHOD ANALYSIS--
SELECT 
    PAYMENTMETHOD, COUNT(PAYMENTID) AS PAYMENTCOUNT
FROM
    sales360payment
GROUP BY PAYMENTMETHOD
ORDER BY PAYMENTCOUNT DESC;
-- RETURN AND REFUND ANALYSIS--
-- QUERY TOTAL RETURN QUALITY --
SELECT 
    SUM(RETURNEQNTY) AS TOTALRETURNQNTY
FROM
    sales360return;
-- QUERY RETURN BY REASON--
SELECT 
    RETURNRSN, SUM(RETURNEQNTY) AS RETURNQNTY
FROM
    sales360return
GROUP BY RETURNRSN
ORDER BY RETURNQNTY DESC;
-- QUERY RETURN BY MONTH --
SELECT 
    SUM(RETURNEQNTY) AS RETURNQNTY,
    MONTH(RETUENDATE) AS RETURNMONTH
FROM
    sales360return
WHERE
    RETUENDATE IS NOT NULL
GROUP BY MONTH(RETUENDATE)
ORDER BY RETURNMONTH;
SELECT 
    MONTH(STR_TO_DATE(RETUENDATE, '%m/%d/%y')) AS returnmnth,
    SUM(RETURNEQNTY) AS TOTALTRETURN
FROM
    sales360return
GROUP BY MONTH(STR_TO_DATE(RETUENDATE, '%m/%d/%y'))
ORDER BY returnmnth;
-- sales and return analysis--
SELECT 
    ORDERID, COUNT(*) AS REFUNDRECORDS
FROM
    sales360_order
GROUP BY ORDERID
HAVING COUNT(*) > 1;
SELECT 
    SUM(O.QUANTITY) AS TOTALQUANTITY,
    SUM(COALESCE(R.RETURNEQNTY, 0)) AS TOTALRETURNQNTY
FROM
    sales360_order O
        LEFT JOIN
    sales360return R ON O.ORDERID = R.RETURNEQNTY;
SELECT 
    COUNT(*) AS MACHEDORDERS
FROM
    sales360_order O
        INNER JOIN
    sales360return R ON O.ORDERID = R.ORDERID;
-- Query for top 10 customer--
SELECT 
    O.CUSTOMERID, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product p ON O.PRODUCTID = P.PRODUCTID
GROUP BY O.CUSTOMERID
ORDER BY TOTALSALES LIMIT 10;
-- QUERY PRODUCT WHOSE PRICE IS HIGHER THAN THE AVERAGE PRODUCT PRICE--
SELECT round(AVG(UNITPRICE),2) FROM sales360product;
SELECT 
    PRODUCTNAME, UNITPRICE
FROM
    sales360product
WHERE
    UNITPRICE > (SELECT 
            AVG(UNITPRICE)
        FROM
            sales360product);
-- WINDOW FUNCTION--
-- QUERY TO RANK EMPLOYEEBY THEIR SALES--
SELECT O.EMPLOYEEID, SUM(O.QUANTITY * P. UNITPRICE) AS TOTALSALES,
RANK() OVER( ORDER BY  SUM(O.QUANTITY * P. UNITPRICE) DESC) AS SALESRANK FROM sales360_order O JOIN 
sales360product P ON O.PRODUCTID = P.PRODUCTID GROUP BY O.EMPLOYEEID; 

-- GIVE EACH EMPLOYEE A UNIQUE NUMBER BASED ON TOTAL SALES ,HIGHEST SALES FIRST--

SELECT O.EMPLOYEEID, SUM(O.QUANTITY * P. UNITPRICE) AS TOTALSALES,
ROW_NUMBER () OVER( ORDER BY  SUM(O.QUANTITY * P. UNITPRICE) DESC) AS ROW_NUM FROM sales360_order O JOIN 
sales360product P ON O.PRODUCTID = P.PRODUCTID GROUP BY O.EMPLOYEEID;
-- BUSINESS RELATED QUESTIONS--
-- 1 . WHICH PRODUCT GENERATE HIGHEST TOTAL SALES--
SELECT 
    P.PRODUCTNAME, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
GROUP BY P.PRODUCTNAME
ORDER BY TOTALSALES DESC
LIMIT 10;
# PRODUCTNAME, TOTALSALES
-- Lenovo Business Laptop IS HIGHEST PRODUCT WITH HIGHEST SALES--
-- query which customer genrate highest sales--
SELECT 
    O.CUSTOMERID, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product p ON O.PRODUCTID = P.PRODUCTID
GROUP BY O.CUSTOMERID;
-- C001  CUSTOMER GENERATED HIGEST SALES--
-- WHAT IS TOTAL SALES GENERATED--
SELECT 
    O.ORDERID, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
GROUP BY O.ORDERID
ORDER BY TOTALSALES DESC;
-- WHAT IS MONTHLY SALES--
SELECT O.ORDERID , date_format(O.ORDERDATE,'%Y-%M') AS SALESMONTH  ,SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES 
FROM sales360_order O JOIN sales360product P ON O.QUANTITY = P.UNITPRICE  
GROUP BY date_format(O.ORDERDATE,'%Y-%M') ORDER BY SALESMONTH;
-- HIGHEST SUBCATEGORY SALES--
  SELECT P.SUBCATEGORY , SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
GROUP BY P.SUBCATEGORY 
ORDER BY TOTALSALES DESC;
 -- LAPTOP IS THE HIGHEST SELLING SUBCATEGORY BASED ON TOTAL SALES --
 -- WHAT ARE TOP 10 PRODUCTS--
SELECT 
    P.PRODUCTNAME, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
GROUP BY P.PRODUCTNAME
ORDER BY TOTALSALES DESC
LIMIT 10;
-- Lenovo Business Laptop ,Portable Projector,Conference Table,Standing Desk, Dell 24-inch Monitor,
-- HP Laser Printer, Executive Office Desk,Noise Cancelling Headphones,External SSD 1TB,Office Chair Pro, 1529820
-- WHICH PRODUCT HAVE HIGHEST QUANTITY SOLD --
SELECT 
    P.PRODUCTNAME, SUM(O.QUANTITY) AS TOTALQUANTITY
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
GROUP BY P.PRODUCTNAME
ORDER BY TOTALQUANTITY DESC;
-- Noise Cancelling Headphones, 232 IS THE HIGHEST QUANTITY SOLD --

-- WHICH PAYMENT METHOD IS MOST COMMONLY USED BY CUSTOMERS ?--
SELECT 
    PAYMENTMETHOD, COUNT(*) AS TOTALPAYMENTS
FROM
    sales360payment
GROUP BY PAYMENTMETHOD
ORDER BY TOTALPAYMENTS DESC;
-- UPI PAYMENT METHOD IS MOST COMMONLY USED BY CUSTOMERS --

-- WHAT IS DISTRIBUTTION OF PAYMENT STATUS? --
SELECT PAYMENTSTATUS, COUNT(*) AS TOTALPAYMENT FROM sales360payment GROUP BY PAYMENTSTATUS
 ORDER BY TOTALPAYMENT DESC  ;
 -- Completed, 1818,Failed, 53,Pending, 129 -
 
 -- WHAT IS TOTAL QUANITY OF PRODUCT RETURN?--
 SELECT SUM(RETURNEQNTY) AS TOTALRETURNQNTY FROM sales360return;
 -- TOTAL 353 RETURN QUANTITY-- 
 
 -- WHICH REASON RETURN IS MOST COMMON --
SELECT 
    RETURNRSN, SUM(RETURNEQNTY) AS TOTALRETURNQNTY
FROM
    sales360return
GROUP BY RETURNRSN
ORDER BY TOTALRETURNQNTY DESC;
 -- WHICH IS HIGHEST RETURN QUANTITY--
SELECT 
    DATE_FORMAT(RETUENDATE, '%Y-%M') AS RETURNMONTH,
    SUM(RETURNEQNTY) AS TOTALRETURN
FROM
    sales360return
GROUP BY DATE_FORMAT(RETUENDATE, '%Y-%M')
ORDER BY TOTALRETURN DESC;
-- WHICH EMPOYEE GENRATE HIGHEST SALES--
SELECT 
    O.EMPLOYEEID, SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES
FROM
    sales360_order O
        JOIN
    sales360product p ON O.PRODUCTID = P.PRODUCTID
GROUP BY O.EMPLOYEEID ORDER BY TOTALSALES DESC ;
 -- WHICH PRODUCT CATEGORY HAVE HIGHEST RETURN QUANNTITY--
 SELECT 
    P.CATEGORY, SUM(R.RETURNEQNTY) AS TOTALRETURN
FROM
    sales360return R
        JOIN
    sales360_order O ON R.ORDERID = O.ORDERID
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
GROUP BY P.CATEGORY
ORDER BY TOTALRETURN DESC;
-- WHICH PRODUCT HAVE HIGHEST RETURN AND HIGHEST SALES--
SELECT 
    P.PRODUCTNAME,
    SUM(O.QUANTITY * P.UNITPRICE) AS TOTALSALES,
    SUM(R.RETURNEQNTY) AS TOTALRETURN
FROM
    sales360_order O
        JOIN
    sales360product P ON O.PRODUCTID = P.PRODUCTID
        LEFT JOIN
    sales360return R ON O.ORDERID = R.ORDERID
GROUP BY P.PRODUCTNAME
HAVING SUM(R.RETURNEQNTY) > 0
ORDER BY TOTALSALES DESC;




 
 
 
 
 



 















